Repository minturtle/CareerSupport, pull requests merged in 2024-10, with the labels that each got.

#26 Feature: Logging 시스템 구축
  build.gradle
  src/main/java/org/minturtle/careersupport/common/aop/Logging.java
  src/main/java/org/minturtle/careersupport/common/aop/LoggingAspect.java
  src/main/java/org/minturtle/careersupport/common/dto/RequestInfo.java
  src/main/java/org/minturtle/careersupport/common/filter/logging/LoggingFilter.java
  src/main/java/org/minturtle/careersupport/common/utils/NanoIdGenerator.java
  src/main/java/org/minturtle/careersupport/interview/repository/InterviewMessageRepository.java
  src/main/java/org/minturtle/careersupport/interview/repository/InterviewTemplateRepository.java
  src/main/java/org/minturtle/careersupport/interview/service/InterviewService.java
  src/main/java/org/minturtle/careersupport/user/repository/UserRepository.java
  src/main/java/org/minturtle/careersupport/user/service/UserService.java
  src/main/resources/logback-spring.xml
Labels: feature

#27 feat: add Logging annotation
  src/main/java/org/minturtle/careersupport/auth/utils/JwtTokenProvider.java
Labels: feature

#30 Test: 테스트 코드 database의 데이터를 모두 지우는 로직 개선
  build.gradle
  src/test/java/org/minturtle/careersupport/common/BlockHoundTest.java
  src/test/java/org/minturtle/careersupport/interview/controller/InterviewControllerTest.java
  src/test/java/org/minturtle/careersupport/testutils/IntegrationTest.java
  src/test/java/org/minturtle/careersupport/user/controller/UserControllerTest.java
  src/test/resources/application.yml
Labels: test

#33 Feature: 코드리뷰 봇 Interface 및 Controller 개발
  src/main/java/org/minturtle/careersupport/auth/filter/ApiTokenFilter.java
  src/main/java/org/minturtle/careersupport/codereview/controller/CodeReviewController.java
  src/main/java/org/minturtle/careersupport/codereview/dto/CodeReviewRequest.java
  src/main/java/org/minturtle/careersupport/codereview/service/AiCodeReviewClient.java
  src/main/java/org/minturtle/careersupport/codereview/service/CodeReviewService.java
  src/main/java/org/minturtle/careersupport/common/config/SecurityConfig.java
  src/main/java/org/minturtle/careersupport/common/utils/Base64Utils.java
  src/test/java/org/minturtle/careersupport/codereview/controller/CodeReviewControllerTest.java
  src/test/java/org/minturtle/careersupport/common/utils/Base64UtilsTest.java
  src/test/java/org/minturtle/careersupport/testutils/IntegrationTest.java
Labels: feature

#36 Feature: Career Support용 API Access Token 발급, 저장 기능
  src/main/java/org/minturtle/careersupport/auth/filter/ApiTokenFilter.java
  src/main/java/org/minturtle/careersupport/auth/utils/ApiTokenProvider.java
  src/main/java/org/minturtle/careersupport/common/config/SecurityConfig.java
  src/main/java/org/minturtle/careersupport/common/controller/CommonController.java
  src/main/java/org/minturtle/careersupport/common/exception/InternalServerException.java
  src/main/java/org/minturtle/careersupport/common/utils/ReactiveEncryptUtils.java
  src/main/java/org/minturtle/careersupport/user/controller/UserController.java
  src/main/java/org/minturtle/careersupport/user/dto/UserApiAccessTokenResponse.java
  src/main/java/org/minturtle/careersupport/user/dto/UserInfoDto.java
  src/main/java/org/minturtle/careersupport/user/entity/User.java
  src/main/java/org/minturtle/careersupport/user/service/UserService.java
  src/test/java/org/minturtle/careersupport/auth/utils/ApiTokenProviderTest.java
  src/test/java/org/minturtle/careersupport/codereview/controller/CodeReviewControllerTest.java
  src/test/java/org/minturtle/careersupport/common/controller/CommonControllerTest.java
  src/test/java/org/minturtle/careersupport/common/utils/ReactiveEncryptUtilsTest.java
  src/test/java/org/minturtle/careersupport/interview/controller/InterviewControllerTest.java
  src/test/java/org/minturtle/careersupport/testutils/IntegrationTest.java
  src/test/java/org/minturtle/careersupport/user/controller/UserControllerTest.java
  src/test/resources/application.yml
Labels: feature

#38 Refactor: Code Review Controller 및 인터페이스 재작성
  src/main/java/org/minturtle/careersupport/codereview/controller/CodeReviewController.java
  src/main/java/org/minturtle/careersupport/codereview/dto/CodeReviewRequest.java
  src/main/java/org/minturtle/careersupport/codereview/dto/PullRequestFile.java
  src/main/java/org/minturtle/careersupport/codereview/service/AiCodeReviewClient.java
  src/main/java/org/minturtle/careersupport/codereview/service/CodeReviewService.java
  src/test/java/org/minturtle/careersupport/codereview/controller/CodeReviewControllerTest.java
Labels: refactor

#42 Feature: AiCodeReviewClient 인터페이스 구현
  src/main/java/org/minturtle/careersupport/codereview/service/AiCodeReviewClient.java
  src/main/java/org/minturtle/careersupport/codereview/service/AiCodeReviewClientImpl.java
  src/main/resources/application-prod.yml
  src/test/resources/application.yml
Labels: feature

#43 Feat ure: Github API 통신 엔드포인트 구현
  build.gradle
  src/main/java/org/minturtle/careersupport/codereview/service/AiCodeReviewClient.java
  src/main/java/org/minturtle/careersupport/codereview/service/GithubCodeReviewService.java
  src/test/java/org/minturtle/careersupport/codereview/controller/CodeReviewControllerTest.java
  src/test/java/org/minturtle/careersupport/testutils/IntegrationTest.java
Labels: feature

#45 Feature: CodeReviewService 리팩터링,파일 WhiteList 필터링 기능 추가
  src/main/java/org/minturtle/careersupport/codereview/dto/CodeReviewRequest.java
  src/main/java/org/minturtle/careersupport/codereview/service/GithubCodeReviewService.java
  src/main/java/org/minturtle/careersupport/common/facade/GithubPullRequestFacade.java
  src/main/java/org/minturtle/careersupport/common/utils/GithubUtils.java
  src/test/java/org/minturtle/careersupport/codereview/controller/CodeReviewControllerTest.java
  src/test/java/org/minturtle/careersupport/codereview/service/GithubCodeReviewServiceTest.java
  src/test/java/org/minturtle/careersupport/testutils/IntegrationTest.java
  src/test/resources/application.yml
Labels: feature

#51 refactor: AI Codereview 응답 스키마 변경
  src/main/java/org/minturtle/careersupport/codereview/controller/CodeReviewController.java
  src/main/java/org/minturtle/careersupport/codereview/service/AiCodeReviewClient.java
  src/main/java/org/minturtle/careersupport/codereview/service/AiCodeReviewClientImpl.java
  src/main/java/org/minturtle/careersupport/codereview/service/CodeReviewService.java
  src/main/java/org/minturtle/careersupport/codereview/service/GithubCodeReviewService.java
  src/main/java/org/minturtle/careersupport/common/dto/CommonResponseBody.java
  src/main/java/org/minturtle/careersupport/common/facade/GithubPullRequestFacade.java
  src/test/java/org/minturtle/careersupport/codereview/controller/CodeReviewControllerTest.java
  src/test/java/org/minturtle/careersupport/codereview/service/GithubCodeReviewServiceTest.java
Labels: refactor
